# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-25 14:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20170323_1918'),
        ('asset', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('tag', models.CharField(max_length=50, verbose_name='TAG')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modificado em')),
            ],
            options={
                'ordering': ['tag'],
                'verbose_name': 'TAG do Ativo',
                'verbose_name_plural': 'TAGs dos Ativos',
            },
        ),
        migrations.CreateModel(
            name='ControlMesh',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modificado em')),
            ],
            options={
                'ordering': ['equipment'],
                'verbose_name': 'Malha de controle',
                'verbose_name_plural': 'Malhas de controle',
            },
        ),
        migrations.CreateModel(
            name='ControlMeshTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('tag', models.CharField(max_length=50, verbose_name='TAG')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modificado em')),
                ('controlmesh', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asset.ControlMesh', verbose_name='Malha de controle')),
            ],
            options={
                'ordering': ['tag'],
                'verbose_name': 'TAG da Malha de controle',
                'verbose_name_plural': 'TAGs das Malhas de controle',
            },
        ),
        migrations.CreateModel(
            name='Criticalness',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=4, verbose_name='Código')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modificado em')),
            ],
            options={
                'ordering': ['code'],
                'verbose_name': 'Criticidade',
                'verbose_name_plural': 'Criticidades',
            },
        ),
        migrations.RemoveField(
            model_name='repair',
            name='manufacturer',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='asset',
        ),
        migrations.AlterModelOptions(
            name='asset',
            options={'ordering': ['equipment', 'assetType'], 'verbose_name': 'Ativo', 'verbose_name_plural': 'Ativos'},
        ),
        migrations.RemoveField(
            model_name='asset',
            name='repair',
        ),
        migrations.AlterField(
            model_name='asset',
            name='equipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Equipment', verbose_name='Equipamento'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='manufacturer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.Manufacturer', verbose_name='Fabricante'),
        ),
        migrations.DeleteModel(
            name='Repair',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
        migrations.AddField(
            model_name='controlmesh',
            name='asset',
            field=models.ManyToManyField(blank=True, to='asset.Asset', verbose_name='Ativos'),
        ),
        migrations.AddField(
            model_name='controlmesh',
            name='assetType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='asset.AssetType', verbose_name='Tipo de malha'),
        ),
        migrations.AddField(
            model_name='controlmesh',
            name='criticalness',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='asset.Criticalness', verbose_name='Criticidade'),
        ),
        migrations.AddField(
            model_name='controlmesh',
            name='equipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Equipment', verbose_name='Equipamento'),
        ),
        migrations.AddField(
            model_name='assettag',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asset.Asset', verbose_name='Ativo'),
        ),
        migrations.AddField(
            model_name='asset',
            name='criticalness',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='asset.Criticalness', verbose_name='Criticidade'),
        ),
    ]
