# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-26 01:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0002_auto_20170325_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='criticalness',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='asset.Criticalness', verbose_name='Criticidade'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='manufacturer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.Manufacturer', verbose_name='Fabricante'),
        ),
    ]
